# Prometheus configuration for GraphSense Avian monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # GraphSense REST API metrics
  - job_name: "graphsense-rest"
    static_configs:
      - targets: ["graphsense-rest:9000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # Cassandra metrics (if JMX exporter is enabled)
  - job_name: "cassandra"
    static_configs:
      - targets: ["cassandra:7070"]
    scrape_interval: 30s

  # Spark metrics
  - job_name: "spark-master"
    static_configs:
      - targets: ["spark-master:8080"]
    metrics_path: "/metrics/prometheus"
    scrape_interval: 30s

  # System metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
    scrape_interval: 15s
